# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: tugas

on:
  push:
    branches:
      - 'issue-*'
  pull_request:
    branches: [ develop ]

jobs:
  build:
    services:
    # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:11
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          tm_pg__password: ${{ secrets.POSTGRES_PASSWORD }}
          tm_pg__database: ${{ secrets.POSTGRES_DB }}
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      minio:
        image: store/minio/minio:RELEASE.2020-12-29T23-29-29Z
        env:
          MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
          MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
          tm_minio__accessKey: ${{ secrets.MINIO_ACCESS_KEY }}
          tm_minio__secretKey: ${{ secrets.MINIO_SECRET_KEY }}
        ports:
          - 9000:9000
      nats:
        image: nats:latest
        env:
          tm_nats__port: ${{ secrets.NATS_PORT }}
        ports:
          - 4222:4222
  
    runs-on: ubuntu-latest
    env:
      ## add secret on settings-secret-add new secret e.g name=POSTGRES_PASSWORD value=mypassword
      tm_server__taskPort: 7002
      tm_server__workerPort: 7001
    defaults:
      run:
        working-directory: ./tugas
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Run Install Dependencies
      run: npm i
    # - name: Run Test Linter
    #   run: npm run lint
    - name: Run Integration Test
      run: npm test
